package greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xiuyuan.vnews.db.VNewsEntity;

import greendao.VNewsEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig vNewsEntityDaoConfig;

    private final VNewsEntityDao vNewsEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        vNewsEntityDaoConfig = daoConfigMap.get(VNewsEntityDao.class).clone();
        vNewsEntityDaoConfig.initIdentityScope(type);

        vNewsEntityDao = new VNewsEntityDao(vNewsEntityDaoConfig, this);

        registerDao(VNewsEntity.class, vNewsEntityDao);
    }
    
    public void clear() {
        vNewsEntityDaoConfig.clearIdentityScope();
    }

    public VNewsEntityDao getVNewsEntityDao() {
        return vNewsEntityDao;
    }

}
